name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Base Module
        run: cd common-base-module && mvn clean install -DskipTests
      - name: Build Project
        run: cd cs544-202403-project && mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t hafeezurrahmansaleh/ea-springboot .
      - name: Publish image to docker hub
        run: docker push hafeezurrahmansaleh/ea-springboot:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull hafeezurrahmansaleh/ea-springboot:latest
      - name: Delete old container
        run: sudo docker rm -f ea-springboot-container
      - name: Run docker container
        uses: docker/run-action@v2
        with:
          image: hafeezurrahmansaleh/ea-springboot:latest
          name: ea-springboot-container
          ports: "8080:8080"
          detach: true
          use_sudo: true
            # Add other options as needed
#        run: docker run -d -p 8080:8080 --name ea-springboot-container hafeezurrahmansaleh/ea-springboot

